exclude: '^$'
fail_fast: false
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1-1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
